path: /media/voanhnhat/SDD_OUTSIDE1/PROJECT_DETECT_OBJECT/data
train: data/hybrid_data
val: data/hybrid_data
test: data/hybrid_data

nc: 18
names:
  0: person
  1: toothbrush
  2: chair
  3: handbag
  4: tv
  5: backpack
  6: cup
  7: bowl
  8: dining_table
  9: book
  10: spoon
"person": 1,
    "toothbrush": 2,
    "chair": 3,
    "handbag": 4,
    "tv": 5,
    "backpack": 6,
    "cup": 7,
    "bowl": 8,
    "dining_table": 9,
    "book": 10,
    "spoon": 11
batch: 8
epochs: 50
imgsz: 640
optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0001
  weight_decay: 0.01
lr0: 0.001
weight_decay: 0.0005
augment: True

trainer:
  logging:
    log_dir: /media/voanhnhat/SDD_OUTSIDE1/PROJECT_DETECT_OBJECT/output/experiments/logs 
    log_freq: 100 
    tensorboard_writer: 
      should_log: True

  checkpoint:
    save_dir: /media/voanhnhat/SDD_OUTSIDE1/PROJECT_DETECT_OBJECT/output/experiments/checkpoints
    save_freq: 1

  model:
    name: sam2_hiera_b+_hybrid
    pretrained: true
    use_amp: true
    freeze_encoder: true
    freeze_transformer: true
    train_decoder_only: true
    gradient_checkpointing: true

  data:
    train:
      path: /media/voanhnhat/SDD_OUTSIDE1/PROJECT_DETECT_OBJECT/data/hybrid_data/hybrid_coco.json
    val:
      path: /media/voanhnhat/SDD_OUTSIDE1/PROJECT_DETECT_OBJECT/data/hybrid_data/hybrid_coco.json

  optim:
    optimizer:
      _target_: torch.optim.AdamW
      lr: 1e-4
      weight_decay: 1e-4


  max_epochs: 12
  val_epoch_freq: 1

  accelerator: cuda
  seed_value: 123

runtime:
  cudnn_benchmark: true
  cudnn_deterministic: false
  enable_grad_checkpointing: true
  torch_amp: true
  empty_cache_every_iter: true